config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :documents

  authenticated :user do
    root "documents#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.where(user_id: current_user).order("created_at DESC")
  end

  def new
    @document = current_user.documents.build
  end

  def create
    @document = current_user.documents.build(document_params)

    if @document.save
      redirect_to @document
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to @document
    else
      render 'edit'
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
  end

  private

    def find_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/documents/edit.html.haml
.wrapper_with_padding
  %h1 Edit Document

  = render 'form'
  = link_to "Cancel", documents_path

app/views/documents/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @documents.blank?
      - @documents.each do |doc|
        %a{ href: (url_for [doc]) }
          .doc
            %p.title= link_to doc.title, doc
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create Document!
      %p Start creating documents and organize your life!
      %button= link_to "Create Document", new_document_path

app/views/documents/new.html.haml
.wrapper_with_padding
  %h1 New Document

  = render 'form'

app/views/documents/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @document.title
    %p= simple_format(@document.content)

    .buttons
      = link_to "Edit Doc", edit_document_path(@document), class: "button"
      = link_to "Trash It", document_path(@document), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your life's work
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
  = csp_meta_tag
%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: 'logo'

      %nav
        - if user_signed_in?
          = link_to "Create Document", new_document_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work. Organized, always.
    %button= link_to 'Enter', new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      %h2 Organize
      %p Placerat diam imperdiet. Nec wisi felis gravida vitae semper. Quam pellentesque velit. Nec libero torquent urna dictum dolor. Vivamus a eu in sit ornare est sapien suspendisse scelerisque in lectus. Mauris fringilla qui. Blandit lorem mi in hymenaeos justo natoque.

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to 'Join Now', new_user_registration_path